baseURL: "https://portfolio.elharda.com"
languageCode: en-us
title: Jalal EL HARDA
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags
      weight: 50
    - identifier: search
      name: Search
      url: /search
      weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  defaultTheme: dark
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Hi👋!"
    subtitle: I'm <b>Jalal Eddine</b>, a dedicated SysAdmin with certifications in Microsoft Azure (Entra ID) and Microsoft 365. Doing well at Sully Group, I use my strong skills in system administration to keep our IT setup strong. I'm always learning and getting certifications to stay updated in the fast-changing tech world. Outside of work, I share techie stuff through content creation, talking about what's happening in system administration. 🚀💻
    imageUrl: "home/Jalal.png"
    imageWidth: 240
    imageHeight: 240
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: mailto:jalal@elharda.com
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jalalelharda"
    #- name: "github"
    #  url: "https://github.com/jalal4ever"
    #- name: "youtube"
    #  url: "https://www.youtube.com/c/"
    - name: "cv"
      url: "https://drive.google.com/file/d/1dUIndF4NM4ANwPGiZncKD7NwhZQEi8h4/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
