baseURL: "https://portfolio.elharda.com"
languageCode: fr-FR
title: Jalal EL HARDA
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Accueil
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projets
      url: /projects
      weight: 30
    - identifier: experience
      name: Experiences
      url: /experience
      weight: 40
    - identifier: tags
      name: Tags
      url: /tags
      weight: 50
    - identifier: search
      name: Recherche
      url: /search
      weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  defaultTheme: dark
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Hello👋!"
    subtitle: Je suis <b>Jalal</b>, un Administrateur Systèmes et Réseaux avec 10 ans d’expérience, certifié en Microsoft 365 et SCCM. Curieux et motivé par l'apprentissage continu, je reste à l'affût des évolutions technologiques pour garantir des environnements optimisés et sécurisés. En parallèle, je partage mes compétences en créant du contenu technique, contribuant activement à la communauté IT. 🚀💻
    imageUrl: "home/Jalal.png"
    imageWidth: 240
    imageHeight: 240
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: mailto:jalal@elharda.com
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jalalelharda"
    #- name: "github"
    #  url: "https://github.com/jalal4ever"
    #- name: "youtube"
    #  url: "https://www.youtube.com/c/"
    - name: "cv"
      url: "https://drive.google.com/file/d/1dUIndF4NM4ANwPGiZncKD7NwhZQEi8h4/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
